github.com:
    users:
        Barrot-Agent:
            oauth_token: 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
    git_protocol: https
    user: Barrot-Agent
    oauth_token: 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
