github.com:
    users:
        Barrot-Agent:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Barrot-Agent
